[Interface]
Address = 10.8.1.20/32
DNS = 172.29.172.254, 1.0.0.1
PrivateKey = REPLACE_WITH_PRIVATE_KEY

[Peer]
PublicKey = REPLACE_WITH_SERVER_PUBLIC_KEY
PresharedKey = REPLACE_WITH_PRESHARED_KEY
AllowedIPs = 0.0.0.0/0, ::/0
Endpoint = REPLACE_WITH_ENDPOINT_HOST:REPLACE_WITH_ENDPOINT_PORT
PersistentKeepalive = 25
